### ISSUE TITLE
Using CSV file as database.

### ISSUE THREAD

**Issue by kaustubhharapanahalli** [vineethvs23/Assignments#2]
Use CSV file to serve as a database to add, view, mark done and remove your todo tasks.

**Comment by vineethvs23** [comment]
CSV not working on my laptop.

**Comment by kaustubhharapanahalli** [comment]
Okay, try to use tabulate method to generate tables in your command prompt. Go through the documentation of tabulate. Implement it to show the contents of todo, done in a table.

I have shared the link for tabulate method below:
https://pypi.python.org/pypi/tabulate
